#! /bin/bash

#SBATCH --job-name=script_name
#SBATCH --output=/cellar/users/ckmah/logs/%A_%a.out    // %A = job name, %a = job number 
#SBATCH --error=/cellar/users/ckmah/logs/%A_%a.error
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5G       // equivalent to: -l h_vmem=5G
#SBATCH --array=1-2:1%50     // colon 2 = step size 2 (e.g. 1, 3, 5...), %100 = max concurrent, 

echo "task: " $SLURM_ARRAY_TASK_ID 

